### PR TITLE
Ant task to download file from S3

### PR DESCRIPTION
**Pull request by arjenvanderende**
Adds an Ant task to download a single file from S3.

We use S3 in our CI environment to store build artifacts. This Ant task allows us to retrieve a build from S3 and deploy it somewhere.

### CODE REVIEW

**Comment by wdalmut** [comment]
Thanks for this PR!

**Comment by arjenvanderende** [comment]
You're welcome. Feels good to contribute to a nice project :-)

**Comment by wiicode** [comment]
I just started using s3get today and I am finding it is extremely slow to transfer data.  It takes ~4 minutes to get about 8Mb.   Not sure what I can do about it, would appreciate suggestions.

``` ant
<taskdef name="s3get" 
classpath="./ant/aws-ant-tasks-0.5-SNAPSHOT.jar" 
classname="it.corley.ant.S3GetTask" />
    <s3get endpoint="${aws.endpoint}"
               key="${aws.accessID}" secret="${aws.secretKey}"
               bucket="${aws.bucket}" src="${f1}"
               dest="${dir.dist}/${f1}" />
```

**Comment by wdalmut** [comment]
Hi,

thanks for your email. I will try a similar situation in these days and
after i came back to you with my results.

Cheers
Walter

Walter

**Pull request merged**
