### PR TITLE
Added Quantity field for CloudFront task required based on Amazon 2012-05-05 update

### PR DESCRIPTION
**Pull request by EliEladElrom**
Fix is needed see: http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/CreateInvalidation.html

"Beginning with the 2012-05-05 version of the CloudFront API, we made substantial changes to the format of the XML document that you include in the request body when you create or update a download distribution or a streaming distribution, and when you invalidate objects. With previous versions of the API, we discovered that it was too easy to accidentally delete one or more values for an element that accepts multiple values, for example, CNAMEs and trusted signers. Our changes for the 2012-05-05 release are intended to prevent these accidental deletions and to notify you when there's a mismatch between the number of values you say you're specifying in the Quantity element and the number of values you're actually specifying."

### CODE REVIEW

**Comment by EliEladElrom** [comment]
Also added the ability to add a file string instead of using the <delete> declarative tag in Ant for cases where you need to loop through a list in order to generate the list of files so you can pass the string and the java will split and process instead of using the delete tag.

**Comment by wdalmut** [comment]
looks great!!

actually i'm out of office for a couple of weeks. i'll review and merge asap!!

thank you so much.

walter

**Comment by EliEladElrom** [comment]
Thank you for sharing and writing clean code. Top notch!

**Comment by wdalmut** [comment]
Thanks! ;-)

**Pull request merged**
