### PR TITLE
Support for DefaultAWSCredentialsProviderChain

### PR DESCRIPTION
**Pull request by q42jaap**
This is useful when a build is run from an ec2 instance (where role information is provided)

### CODE REVIEW

**Comment by wdalmut** [comment]
This could be related to #20 can you join both PR just one PR and squash this 2 commits into one?

I have just to check and merge one PR.

Can you do it? Can you also add your name to contributor list in README.md file?

Thanks
Walter

**Comment by q42jaap** [comment]
These are two different things, if you could first merge #20, I will make a
new PR with just the DefaultAWSCredentialsProviderChain commit, how does
that sound

Jaap Taal

[ Q42 | tel 070 44523 42 | direct 070 44523 65 | http://q42.nl |
Waldorpstraat 17F, Den Haag | Oostelijke Handelskade 749, Amsterdam | KvK
30164662 ]

**Comment by wdalmut** [comment]
You right, sorry.

I merge probably today your first PR. Thanks again!

Walter

**Comment by q42jaap** [comment]
You're welcome!

Jaap Taal

[ Q42 | tel 070 44523 42 | direct 070 44523 65 | http://q42.nl |
Waldorpstraat 17F, Den Haag | Oostelijke Handelskade 749, Amsterdam | KvK
30164662 ]

**Pull request closed without merging**
